apiVersion: v2
name: openreports
description: A Helm chart for installing openreports APIs.
version: v0.0.0
appVersion: latest
annotations:
  artifacthub.io/operator: "false"
  artifacthub.io/prerelease: "false"

