name: release-helm

permissions: {}

on:
  push:
    tags:
      - reports-api-v*

jobs:
  lint-artifacthub:
    runs-on: ubuntu-latest
    container:
      image: artifacthub/ah
      options: --user root
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: Run ah lint
        working-directory: ./charts/
        run: ah lint
  
  create-helm-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
      id-token: write
      pages: write
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: Setup-build-env
        uses: ./.github/actions/setup-build-env
        timeout-minutes: 10
      - name: Install helm
        uses: azure/setup-helm@b9e51907a09c216f16ebe8536097933489208112 # v4.3.0
        with:
          version: v3.10.3
        
      - name: Install Cosign
        uses: sigstore/cosign-installer@fb28c2b6339dcd94da6e4cbcbc5e888961f6f8c3 # v3.9.0
      
      - name: Set version
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

      - name: Create charts tmp directory
        run: |
          mkdir -p charts-tmp
          cp -a chart chart-tmp/reports-api
      
      - name: Run chart-releaser
        uses: stefanprodan/helm-gh-pages@0ad2bb377311d61ac04ad9eb6f252fb68e207260 #v1.7.0
        with:
          token: "${{ secrets.GITHUB_TOKEN }}"
          linting: off
          charts_dir: charts-tmp
      
      - name: Login to GitHub container registry
        run: |
          helm registry login ghcr.io -u ${GITHUB_ACTOR} -p ${{ secrets.GITHUB_TOKEN }}
      
      - name: Publish OCI Chart
        run: |
          helm package chart-tmp/reports-api --destination .dist/
          helm push .dist/reports-api-*.tgz oci://ghcr.io/${{ github.repository_owner }}/charts |& tee .digest
          cosign login --username ${GITHUB_ACTOR} --password ${{ secrets.GITHUB_TOKEN }} ghcr.io
          cosign sign --yes ghcr.io/${{ github.repository_owner }}/charts/reports-api@${cat .digest | awk -F "[, ]" '/Digest/{print $NF}'}

